feat!: add lockfile generation support
The changes in this PR are born out of the research spike to find the
best way to add lockfile generation support to the `phylum-ci` image.
Each [required tool](https://docs.phylum.io/docs/lockfile_generation)
was examined, to find out how much overhead it would add to the image in
each of the various ways it could be installed. The results of which are
documented in the comment trails of this private story:

https://github.com/phylum-dev/roadmap/issues/380

The actions taken here include:

* Update the existing `Dockerfile` to install lockfile generation tools
* Retain the previous functionality with a new `Dockerfile.slim` file
* Switch base image from `python:3.11-slim-bullseye` to `-bookworm`
* Format and refactor throughout
  * Be DRY about the version of `poetry`
  * Ensure `RUN` command contents adhere to `shellcheck` QA findings

BREAKING CHANGE: The `phylum-ci` docker image created from the default
`Dockerfile` is much larger, containing *all* the required tools for
lockfile generation across all supported ecosystems. To retain the
previous functionality, a new `slim` tag is offered for those instances
where *no* manifest files are present and/or *only* lockfiles are used.

diff --git a/Dockerfile.slim b/Dockerfile.slim
--- a/Dockerfile.slim
+++ b/Dockerfile.slim
@@ -1,6 +1,14 @@
 # syntax=docker/dockerfile:1
 # The syntax statement above is to make use of buildkit's build mounts for caching
 
+# NOTE:
+# This Dockerfile is used to build the `slim` tags for the `phylum-ci` images. It differs
+# from the primary Dockerfile in that it does not install the required tools needed for
+# lockfile generation: https://docs.phylum.io/docs/lockfile_generation (with the exception
+# of the `pip` tool). The image created from this Dockerfile is significantly smaller and
+# will allow the integrations relying on it to complete faster. It is useful for those
+# instances where *no* manifest files are present and/or *only* lockfiles are used.
+
 ##########################################################################################
 # This Dockerfile makes use of BuildKit mode, which needs to be enabled client side first:
 #
@@ -107,7 +115,7 @@ RUN --mount=type=cache,id=pip,target=/root/.cache/pip \
     set -eux; \
     ${PHYLUM_VENV_PIP} cache info; \
     ${PHYLUM_VENV_PIP} cache list; \
-    ${PHYLUM_VENV_PIP} install -r requirements.txt pipenv poetry==${POETRY_VERSION}
+    ${PHYLUM_VENV_PIP} install -r requirements.txt
 COPY "${PKG_SRC:-.}" .
 RUN ${PHYLUM_VENV_PIP} install --no-cache-dir ${PKG_NAME:-.}
 RUN find ${PHYLUM_VENV} -type f -name '*.pyc' -delete
@@ -132,108 +140,27 @@ ARG PHYLUM_API_URI
 # and therefore increase the API rate limit.
 ARG GITHUB_TOKEN
 
-# Ref: https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope
-ARG TARGETOS
-ARG TARGETARCH
-
 LABEL maintainer="Phylum, Inc. <engineering@phylum.io>"
 LABEL org.opencontainers.image.source="https://github.com/phylum-dev/phylum-ci"
 
 ENV PHYLUM_VENV="/opt/venv"
-
-ENV GRADLE_PATH="/opt/gradle/bin"
-ENV GO_PATH="/usr/local/go/bin"
-ENV CARGO_PATH="/root/.cargo/bin"
-ENV PATH=${PHYLUM_VENV}/bin:$PATH:${GRADLE_PATH}:${GO_PATH}:${CARGO_PATH}
-
+ENV PATH=${PHYLUM_VENV}/bin:$PATH
 ENV PYTHONDONTWRITEBYTECODE=1
 
-# Ref: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables
-ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
-ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
-ENV DOTNET_NOLOGO=1
-
-# Copy only Python packages to limit the image size. This includes the `phylum` package with it's
-# `phylum-ci` and `phylum-init` entry points, plus the `pip`, `pipenv`, and `poetry` required tools.
+# Copy only Python packages to limit the image size. This includes the
+# `phylum` package with it's `phylum-ci` and `phylum-init` entry points.
 COPY --from=builder ${PHYLUM_VENV} ${PHYLUM_VENV}
 
-# Specify the shell options here, based on the use of pipelines.
-# Ref: https://github.com/hadolint/hadolint/wiki/DL4006
-SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]
-RUN \
-    # Install pre-requisites and package manager versions for `npm`, `bundle`, and `mvn` tools
+RUN set -eux; \
+    # Install pre-requisites
     apt-get update; \
     apt-get upgrade --yes; \
-    apt-get install --yes --no-install-recommends \
-        git \
-        npm \
-        bundler \
-        maven \
-        curl \
-        unzip \
-        jq \
-        ; \
+    apt-get install --yes --no-install-recommends git; \
     # Make ENTRYPOINT alternative script available
     chmod +x "${PHYLUM_VENV}/bin/entrypoint.sh"; \
-    #
     # Install Phylum CLI
     phylum-init -vvv --phylum-release "${CLI_VER:-latest}" --global-install; \
-    #
-    # Install and enable `corepack` with cached instances of the latest major versions of `yarn` and `pnpm` tools
-    npm install -g corepack@latest; \
-    corepack pack yarn@stable pnpm@latest; \
-    corepack enable yarn pnpm; \
-    #
-    # Create an "alias" for `curl` with secure and common options
-    printf '#!/bin/bash\ncurl --proto "=https" --tlsv1.2 -sSfL "$@"\n' > /usr/bin/curls; \
-    chmod +x /usr/bin/curls; \
-    #
-    # Manual install of `gradle`
-    GRADLE_VERSION=$(curls https://services.gradle.org/versions/current | jq -r '.version'); \
-    GRADLE_DL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"; \
-    GRADLE_DL_SHA256=$(curls "${GRADLE_DL}.sha256"); \
-    curls -o gradle.zip "${GRADLE_DL}"; \
-    printf "%s *gradle.zip" "${GRADLE_DL_SHA256}" | sha256sum -c -; \
-    mkdir /opt/gradle; \
-    unzip -d /opt/gradle gradle.zip; \
-    mv /opt/gradle/gradle-"${GRADLE_VERSION}"/* /opt/gradle/; \
-    rm gradle.zip && rmdir "/opt/gradle/gradle-${GRADLE_VERSION}/"; \
-    #
-    # Manual install of `go`
-    # Ref: https://pkg.go.dev/golang.org/x/website/internal/dl
-    GO_DL_URL="https://go.dev/dl/?mode=json"; \
-    GO_DL_REL=$(curls "${GO_DL_URL}" | jq '.[0].files[] | select(.os==env.TARGETOS and .arch==env.TARGETARCH)'); \
-    GO_DL_FILENAME=$(echo "${GO_DL_REL}" | jq -r '.filename'); \
-    GO_DL_SHA256=$(echo "${GO_DL_REL}" | jq -r '.sha256'); \
-    curls -o go.tgz "https://go.dev/dl/${GO_DL_FILENAME}"; \
-    printf "%s *go.tgz" "${GO_DL_SHA256}" | sha256sum -c -; \
-    rm -rf /usr/local/go; \
-    tar -C /usr/local -xzf go.tgz; \
-    rm go.tgz; \
-    #
-    # Manual install of Rust to get `cargo` tool
-    curls https://sh.rustup.rs | sh -s -- -y --profile minimal; \
-    #
-    # Install .NET SDK to get `dotnet` tool
-    # Ref: https://github.com/dotnet/core/tree/main/release-notes
-    DOTNET_SDK_LATEST_CHANNEL_VER=$( \
-        curls https://raw.githubusercontent.com/dotnet/core/main/release-notes/releases-index.json | \
-        jq -r '[."releases-index"[] | select(."support-phase"=="active")] | first."channel-version"' \
-    ); \
-    DEB_MAJ_VER=$(cut -d "." -f1 /etc/debian_version); \
-    curls -o ms-prod.deb "https://packages.microsoft.com/config/debian/${DEB_MAJ_VER}/packages-microsoft-prod.deb"; \
-    dpkg --install ms-prod.deb; \
-    rm ms-prod.deb; \
-    apt-get update; \
-    apt-get install --yes --no-install-recommends "dotnet-sdk-${DOTNET_SDK_LATEST_CHANNEL_VER}"; \
-    #
-    # Final cleanup
-    rm /usr/bin/curls; \
-    apt-get remove --yes --auto-remove \
-        curl \
-        unzip \
-        jq \
-        ; \
+    # Cleanup
     apt-get purge --yes --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
     rm -rf /var/lib/apt/lists/*; \
     rm -rf /tmp/*; \
